# Site settings
title: OCC Strategy & Development
email: nicole@occstrategy.rocks
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.occstrategy.rocks/" # the base hostname & protocol for your site

# twitter_username:
# github_username:

# Build settings
markdown: kramdown
